---
kind: pipeline
type: docker
name: default
globals:
  - &docker_creds
    username:
      from_secret: docker_hub_user
    password:
      from_secret: docker_hub_password
steps:
  - name: prepare
    image: busybox
    commands:
      - mkdir -p /cache/${DRONE_REPO}/docker
    volumes:
      - name: cache
        path: /cache
  - name: build
    image: plugins/docker
    settings:
      repo: nightfuryest/drone-plugin-secret-to-env
      tags:
        - latest
        - ${DRONE_COMMIT_BRANCH}
      create_repository: true
      use_cache: true
      <<: *docker_creds
    volumes:
      - name: docker
        path: /var/lib/docker
volumes:
  - name: cache
    host:
      path: /var/cache
  - name: docker
    host:
      path: /var/cache/${DRONE_REPO}/docker

trigger:
  branch:
    - master
    - production
